### ISSUE TITLE
Python 3 support for long paths doesn't work in Windows 10

### ISSUE THREAD

**Issue by ArekPiekarz** [Alexpux/MINGW-packages#3139] opened 2017-11-12 22:15 UTC
Python 3.6 officially supports paths longer than 260 characters on Windows 10 when opt-in, i.e. [through registry editor](https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation). However, version from Msys2 doesn't support it.

Output from official x64 version:
```
$ /d/app/Python/Python36/python.exe --version
Python 3.6.3
$ /d/app/Python/Python36/python.exe foo.py
path: D:\dev\abcdefghijklmnop0123456789\abcdefghijklmnop0123456789\abcdefghijklmnop0123456789\abcdefghijklmnop0123456789\abcdefghijklmnop0123456789\abcdefghijklmnop0123456789\abcdefghijklmnop0123456789\abcdefghijklmnop0123456789\abcdefghijklmnop0123456789\abcdefghijklmnop0123456789
length: 276
makedirs(path)
ok

```

Output from Msys2 version:
```
$ which python3
/mingw64/bin/python3
$ python3 --version
Python 3.6.3
$ python3 foo.py
path: D:/dev/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789
length: 276
makedirs(path)
failed: [WinError 206] The filename or extension is too long: 'D:/dev/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789/abcdefghijklmnop0123456789'
```

Code to test long path support:
```
import os

path = os.path.abspath("abcdefghijklmnop0123456789/" * 10);
print("path:", path)
print("length:", len(path))

try:
    print("makedirs(path)")
    os.makedirs(path)
    print("ok")
except Exception as error:
    print("failed:", error)
```

**Comment by lazka** [comment] 2017-11-13 08:57
Does `MSYSTEM= python3 foo.py` change anything?

**Comment by ArekPiekarz** [comment] 2017-11-13 18:32
No, it doesn't. However as an additional info I noticed that even without "MSYSTEM=" the script creates 8 nested directories instead of 10, so the created path has 224 characters - below the 260 limit. The exception is still thrown in both cases.

**Comment by lazka** [comment] 2017-11-13 19:05
Ah, right, it has to be enabled for each binary through the manifest: https://github.com/python/cpython/commit/19ab0fd456a79fa1fdfdb543ac423723667cb2d0#diff-d1069d896c8248e2c5ca18c0919f2bb1

(I suggested the MSYSTEM= change, as that changes the path separator from / to \\, which is required for extended Windows paths I think)

**Comment by ArekPiekarz** [comment] 2017-11-13 20:48
What do you mean? I found [on MSDN](https://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29.aspx?f=255&MSPPError=-2147217396#maxpath) that it can either be enabled globally through registry or per app using a manifest. I already enabled it in registry.

**Comment by lazka** [comment] 2017-11-13 20:57
> What do you mean?

I mean that we might need to patch something in the mingw build process to enable this.

**Comment by mati865** [comment] 2017-11-13 21:29
@ArekPiekarz from regedit/gpedit you can enable this feature but if program doesn't "tell" Windows it supports long paths (via manifest) it will fall back to old behaviour (to prevent old programs from breaking).

**Comment by lazka** [comment] 2018-01-22 19:55
I've pushed something in #3310. feedback welcome

**Comment by ArekPiekarz** [comment] 2018-01-23 18:39
@lazka I can see Alexpux merged your commit, so I think the easiest for me would be to wait until he builds and uploads the newer package, then I'll test it.

**Comment by lazka** [comment] 2018-01-23 19:05
@ArekPiekarz yeah. You can also try with the build results of the appveyor run:

https://ci.appveyor.com/api/buildjobs/5dj1e0kk7yvi24qk/artifacts/artifacts%2Fmingw-w64-i686-python3-3.6.4-2-any.pkg.tar.xz

https://ci.appveyor.com/api/buildjobs/cfu761w7dygpfj8r/artifacts/artifacts%2Fmingw-w64-x86_64-python3-3.6.4-2-any.pkg.tar.xz

`pacman -U *.pkg.tar.xz`

**Comment by ArekPiekarz** [comment] 2018-01-23 19:33
I have just tested the python3 x64 from AppVeyor and it fixes the issue with long paths :-). Thanks a lot!

**Comment by lazka** [comment] 2018-01-24 18:21
@ArekPiekarz thanks for testing! Let's close this then.

**Closed by lazka** 2018-01-24 18:21 UTC

**Comment by Anton-V-K** [comment] 2022-05-13 23:17
Just a hint to anyone googling here - there was a bug in Python 3.9.8 (see https://github.com/python/cpython/issues/89935 ) caused by missing manifest in this release.
