### ISSUE TITLE
libpng16 throwing entry point inflateReset2 could not be located

### ISSUE THREAD

**Issue by genusistimelord** [Alexpux/MINGW-packages#813] opened 2015-10-06 20:56 UTC
This seems to just have happened to me today. yesterday everything worked fine then late at night i updated msys2 packages. then today it no longer will run within msys2 and displays the following error.

http://i.imgur.com/zZMESMO.png

(4:33:51 PM) DavidEGrayson: Looking at http://repo.msys2.org/mingw/i686/ , we can see that libpng has not been rebuilt after zlib was updated.  I suspect libpng was configured and built against an older version of zlib and that this causes some mismatch.
(4:33:52 PM) m2bot: Title: Index of /mingw/i686/ (at repo.msys2.org)
(4:35:34 PM) DavidEGrayson: I would make a minimal example to demonstrate the problem and report it as an issue to https://github.com/Alexpux/MINGW-packages  Then someone can try rebuilding libpng and see if that fixes the problem.

**Comment by DavidEGrayson** [comment] 2015-10-06 21:25
By "minimal example", I meant a 10 to 20 line C program, along with the command used to compile it, that one could use to reproduce the problem.  Or if you could just point to some other packaged MSYS2 executable that cannot run because of this problem that would work.  It helps if other people can reproduce the problem on their own machine.

**Comment by outruner** [comment] 2016-03-23 22:05
Hello, I have the same problem with msys2 freshly installed and updated.

**Comment by wthie** [comment] 2016-07-07 22:11
Same problem here, fresh install of MSYS, libpng fails with the error given by OP. I'm using libpng from cairosvg, so this is a blocking issue for a lot of software on top of libpng. I would really appreciate this being solved, as cairo is pointing to msys as the reference for win runtimes. Thank you for your cooperation.

**Comment by mati865** [comment] 2016-07-08 15:56
Like @DavidEGrayson we need to know the way to reproduce issue or it will be ignored, e.g. for me optipng and pngcrush are fine. Since I cannot reproduce it with the software I use I'm not able to help you.

**Comment by elieux** [comment] 2017-02-21 20:16
Closing. But if someone comes up with some steps to reproduce the issue, please post them and we'll try to fix it.

**Closed by elieux** 2017-02-21 20:16 UTC

**Comment by echizenryoma** [comment] 2017-04-27 03:35
I found my high resolution screen has this problem, but other has no problem.

**Comment by DavidEGrayson** [comment] 2017-04-27 05:32
That's pretty hard to believe, but if you can say exactly what steps you took to reproduce the issue then someone might be able to fix it.

**Comment by echizenryoma** [comment] 2017-04-27 06:24
I write a very simple program of opencv, then build it. In my laptop with high resolution(3840x2160) screen, I can run it in MinGW64 Shell, but I can't run it by double click it or in CMD/Powershell. If I double click it, it show that "libpng16-16.dll throwing entry point inflateReset2 could not be located". I add MinGW64/bin into my laptop's SYSTEM PATH. But I can run it by double click it on my other computer which has low resolution(1920x1080) screen. So I guess resolution maybe cause this problem. I hope sir help me solve this problem. Thank you very much.

**Comment by mati865** [comment] 2017-04-27 08:57
It not uncommon for software targeting UNIX to cause problems on Windows with HiDPI screen.
All I can think of is bug in library exposed only in specific scenarios (like HiDPI screen).

Still the is no minimal example or logs.
Strace could bring here some useful info.

**Comment by mati865** [comment] 2017-04-27 10:08
@echizenryoma There might be something else containing `zlib1.dll` in your path. Copy your program, `libpng16-16.dll` and `zlib1.dll` to empty directory and try to run it.

**Comment by Youda008** [comment] 2019-05-20 08:38
So i found the cause. Intel brings in their own `zlib1.dll` in `C:\Program Files\Intel\WiFi\bin\` and they add this directory to PATH. So whenever an app linked against zlib tries to execute without `C:\msys64\mingw64\bin` in PATH, it tries to load this different version of zlib, that doesn't contain the method. The real solution would be to poke into Intel and tell them to stop doing stupid things like plaguing system-wide PATH with their own things, but whatever. Just copy your mingw64 zlib1.dll into your app directory and call it a day.

**Comment by mikyll** [comment] 2021-12-27 02:23
> So i found the cause. Intel brings in their own `zlib1.dll` in `C:\Program Files\Intel\WiFi\bin\` and they add this directory to PATH. So whenever an app linked against zlib tries to execute without `C:\msys64\mingw64\bin` in PATH, it tries to load this different version of zlib, that doesn't contain the method. The real solution would be to poke into Intel and tell them to stop doing stupid things like plaguing system-wide PATH with their own things, but whatever. Just copy your mingw64 zlib1.dll into your app directory and call it a day.

Thank you so much, I have been puzzling on that for about an hour 😂🚀

**Comment by Michaelzhouisnotwhite** [comment] 2023-08-24 11:58
Solved!! Works for me.

> The fix would be to adjust the Order at which the paths Exist within **Path** As Windows does use these in Order. So make sure msys2 path is greater than the Path of other software causing the issue. In this case C:\Program Files\Intel\WiFi\bin. However my issue was a bit different as I was using a AMD Computer. There was another software installed that had a much newer zlib version at the time that was not Intel related. So my fix is to move the msys2 path just after the Main windows directories.
> 
> The other fix is to add the zlib.dll and libpng together in the same directory with the Executable as they will first do any local linking and then do path linking so it will ignore any Paths that are irrelevant.
> 
> I never really got around to posting what the issue was till i saw people replying to this today I forgot all about it.
