### ISSUE TITLE
winpty python2 missing some paths

### ISSUE THREAD

**Issue by chaffra** [Alexpux/MINGW-packages#2031] opened 2016-12-15 14:36 UTC
With the latest msys2 I can do `winpty.exe python2.exe`. However I cannot import logging. It gives me

```
>>> import logging
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mingw64/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
ImportError: No module named time
```

and this ends up breaking ipython

**Comment by lazka** [comment] 2017-07-05 16:13
I can't reproduce with an up-to-date environment. Is this still a problem?

**Comment by lazka** [comment] 2018-01-25 11:40
I guess not, closing.

**Closed by lazka** 2018-01-25 11:40 UTC
