### ISSUE TITLE
Makefile which created by qmake contains both static and dynamic lib. (mingw-w64-i686-qt5-static-5.12.1-2)

### ISSUE THREAD

**Issue by shithappens2016** [Alexpux/MINGW-packages#4970] opened 2019-02-12 16:29 UTC
**mingw-w64-i686-qt5-static-5.12.1-2**

Makefile.Release created by qmake  contains both `/mingw32/lib/libQt5Core.dll.a` and `/mingw32/qt5-static/lib/libQt5Core.a`

**Comment by adipose** [comment] 2019-02-12 21:53
I think it comes from qt_configure.prf

```
            } else {
                # Under Windows, we look only for static libraries, as even for DLLs
                # one actually links against a static import library.
                mingw {
                    lcan += \
                        # MinGW supports UNIX-style library naming in addition to
                        # the MSVC style.
                        lib$${lib}.dll.a lib$${lib}.a \
                        # Fun fact: prefix-less libraries are also supported.
                        $${lib}.dll.a $${lib}.a
                }
                lcan += $${lib}.lib
```

**Comment by adipose** [comment] 2019-02-12 22:29
Or not--that didn't seem to fix it.

**Comment by adipose** [comment] 2019-02-13 00:32
During the qmake, it somehow ends up redirecting over to the dynamic qt libraries (in this case qt5printsupport).

```
DEBUG 1: C:/msys64/mingw32/qt5-static/share/qt5/plugins/bearer/qgenericbearer.prl:6: QMAKE_PRL_LIBS_FOR_CMAKE := -LC:/msys64/mingw32/qt5-static/lib;C:/msys64/mingw32/qt5-static/lib/libQt5Network.a;-ldnsapi;-liphlpapi;-lcrypt32;C:/msys64/mingw32/qt5-static/lib/libQt5Core.a;-lmpr;-lnetapi32;-luserenv;-lversion;-lws2_32;-lkernel32;-luser32;-lshell32;-luuid;-lole32;-ladvapi32;-lwinmm;C:/msys64/mingw32/qt5-static/lib/libqtpcre2.a;C:/msys64/mingw32/qt5-static/../lib/libssl.dll.a;C:/msys64/mingw32/qt5-static/../lib/libcrypto.dll.a;C:/msys64/mingw32/qt5-static/../i686-w64-mingw32/lib/libcrypt32.a;C:/msys64/mingw32/qt5-static/../i686-w64-mingw32/lib/libgdi32.a;;;
DEBUG 1: C:/msys64/mingw32/qt5-static/share/qt5/plugins/bearer/qgenericbearer.prl:6: leaving block, okey=true
DEBUG 1: done visiting file C:/msys64/mingw32/qt5-static/share/qt5/plugins/bearer/qgenericbearer.prl
DEBUG 1:   Replacing library reference qgenericbearer with libqgenericbearer.a
DEBUG 3: Fixed[0,1] ../../../msys64/mingw32/qt5-static/share/qt5/plugins/bearer/qgenericbearer.prl :: to :: ../../msys64/mingw32/qt5-static/share/qt5/plugins/bearer/qgenericbearer.prl [C:/dev/aview/nbproject::C:/dev/aview]
DEBUG 3: Fixed[3,1] C:/msys64/mingw32/lib/gcc/i686-w64-mingw32/7.4.0/Qt5PrintSupport :: to :: ../../../msys64/mingw32/lib/gcc/i686-w64-mingw32/7.4.0/Qt5PrintSupport [C:/dev/aview/nbproject::C:/dev/aview]
DEBUG 2: QMakeMetaInfo: Cannot find info file for ../../../msys64/mingw32/lib/gcc/i686-w64-mingw32/7.4.0/Qt5PrintSupport.prl
DEBUG 3: Fixed[3,1] C:/msys64/mingw32/lib/gcc/Qt5PrintSupport :: to :: ../../../msys64/mingw32/lib/gcc/Qt5PrintSupport [C:/dev/aview/nbproject::C:/dev/aview]
DEBUG 2: QMakeMetaInfo: Cannot find info file for ../../../msys64/mingw32/lib/gcc/Qt5PrintSupport.prl
DEBUG 3: Fixed[3,1] C:/msys64/mingw32/i686-w64-mingw32/lib/Qt5PrintSupport :: to :: ../../../msys64/mingw32/i686-w64-mingw32/lib/Qt5PrintSupport [C:/dev/aview/nbproject::C:/dev/aview]
DEBUG 2: QMakeMetaInfo: Cannot find info file for ../../../msys64/mingw32/i686-w64-mingw32/lib/Qt5PrintSupport.prl
DEBUG 3: Fixed[3,1] C:/msys64/mingw32/lib/Qt5PrintSupport :: to :: ../../../msys64/mingw32/lib/Qt5PrintSupport [C:/dev/aview/nbproject::C:/dev/aview]
DEBUG 2: QMakeMetaInfo: Found info file ../../../msys64/mingw32/lib/Qt5PrintSupport.prl for ../../../msys64/mingw32/lib/Qt5PrintSupport.prl
DEBUG 1: Processing PRL file: ../../../msys64/mingw32/lib/Qt5PrintSupport.prl
DEBUG 1: visiting file C:/msys64/mingw32/lib/Qt5PrintSupport.prl
DEBUG 1: C:/msys64/mingw32/lib/Qt5PrintSupport.prl: entering block

```

**Comment by adipose** [comment] 2019-02-13 05:16
The problem simply seems to be that the library paths are checked in the wrong order by qmake, and /mingw32/lib is checked before /mingw32/qt5-static/lib.  Removing dynamic qt solves the issue, but this is a regression.

**Comment by Alexpux** [comment] 2019-02-13 05:36
@adipose as I understand the problem is in qmake itself. If first try to search libraries and prl files in GCC library paths

**Comment by adipose** [comment] 2019-02-13 05:49
Yes, it seems so.  .qmake.stash has the following:

```
QMAKE_CXX.LIBDIRS = \
    C:/msys64/mingw32/lib/gcc/i686-w64-mingw32/7.4.0 \
    C:/msys64/mingw32/lib/gcc \
    C:/msys64/mingw32/i686-w64-mingw32/lib \
    C:/msys64/mingw32/lib
```

**Comment by adipose** [comment] 2019-02-13 06:53
I've added a line to `qt5-static\share\qt5\mkspecs\win32-g++` :

`QMAKE_DEFAULT_LIBDIRS   += C:/msys64/mingw32/qt5-static/lib`

Resulting .qmake.stash:
```
QMAKE_CXX.LIBDIRS = \
    C:/msys64/mingw32/qt5-static/lib \
    C:/msys64/mingw32/lib/gcc/i686-w64-mingw32/7.4.0 \
    C:/msys64/mingw32/lib/gcc \
    C:/msys64/mingw32/i686-w64-mingw32/lib \
    C:/msys64/mingw32/lib
```

I'm not sure this is the most elegant solution, but given that this mkspec is designed entirely for qt5-static, forcing the library into this file as well seems like a decent hack for now, given how qmake currently behaves.

**Comment by shithappens2016** [comment] 2019-02-13 11:12
One more thing

`libssl.dll.a` and `libcrypto.dll.a` need to be replaced with `libssl.a` and `libcrypto.a` in (*.prl and *.pri).

**Comment by adipose** [comment] 2019-02-13 22:18
I didn't have any issues with those, even though I do use libssl.  What issue are you having?

**Comment by Alexpux** [comment] 2019-02-14 14:23
I hope static builds are fixed in qt5-static-5.12.1-5 package

**Comment by adipose** [comment] 2019-02-14 19:13
Static builds are working for me under -5 package.  Thank you for your help!

**Comment by shithappens2016** [comment] 2019-02-14 23:04
Seems fine now  thanks guys

**Closed** 2019-02-14 23:05 UTC
