### ISSUE TITLE
Qt 5.7.0

### ISSUE THREAD

**Issue by mcallegari** [Alexpux/MINGW-packages#1497] opened 2016-06-20 18:59 UTC
Qt 5.7.0 has been released.

My effort on the qt5-git package is kind of close to be good, but there are still a few issues that I'm not able to figure out.
Everything builds fine, QtWidget examples work fine, basic Quick examples work fine, Qt3D "windowed" examples work fine

BUT

1) I've got a misterious message saying "Unable to find the specified path" for 3 times every time I execute qmake on any example/project. Afterward, everything builds fine and run though

2) Qt3D + Quick examples do not work. They build fine but show a white window and I don't know why. (and that's exactly what I need for my projects :disappointed: )

Can we please join efforts with this 5.7.0 release and make it straight ?

Footnote: obviously QtWebEngine is out of the game. I never even tried to build it.

**Comment by Martchus** [comment] 2016-06-21 14:32
I'm maintaining the mingw-w64-qt5-* cross compiler packages which work very similar and I'm currently upgrading to 5.7.0, too.
Here a link just that you know what I'm talking about: https://github.com/Martchus/PKGBUILDs

Everything seems to build fine except the WebKit module. It seems like you're just building it in the regular (non-Git) version of the package. You might have been trying to build it anyways. Have you also the issue that the build system tries to build some units with the C compiler instead with the C++ compiler which leads to errors like `#include<algorithm>` can not be found?

To your footnote about QtWebEngine: I also gave up on that. However, there is an interesting alternative: https://github.com/annulen/webkit/releases
It is just a preview and I haven't tried to build it yet, but it seems promising.

Unfortunately I can not help you with the issues. Do you use ANGLE or native OpenGL?

**Comment by mcallegari** [comment] 2016-06-25 08:35
AFAIK QtWebkit is no longer included in Qt 5.7.0. The project ran by Konstantin Tokarev is a "reboot" of QtWebkit, but it's not an official module supported by the Qt company. Also, it's still in tech preview, so I don't believe efforts should go in that module at the moment.
Plus, I would keep it separated from the official Qt modules, for several reasons. One above all, the footprint. Not everybody needs a webkit engine, so it should be installed separately "on demand".

As for opengl, I believe ANGLE is still a work in progress here (and doesn't work yet), so ATM I think we build the 'desktop' way

**Comment by Alexpux** [comment] 2016-06-25 08:36
We download and build Webkit module during Qt5 building see PKGBUILD

**Comment by mcallegari** [comment] 2016-06-25 08:43
Ah yes, I forgot about that, but it doesn't make sense anymore with Qt 5.7.0.
You might find unexpected build errors since it is not "officially" maintained anymore.
QtWebEngine should be built...if only it could be built...

I would say we should wait for the QtWebKit reboot to stabilize, and create a new "qt5webkit" package in MSYS, separated from the official Qt modules

**Comment by Martchus** [comment] 2016-06-25 12:35
That the alternative approach by Konstantin Tokarev is not official should be quite obvious. I just mentioned it because of your comment about Qt WebEngine. Currently, I wouldn't put efforts into it, too.

That's why I'm currently still trying to build the current and former officially maintained Qt WebKit module which is now released as a "community release" and has been deprecated.

> Not everybody needs a webkit engine, so it should be installed separately "on demand".

This is true. In fact, my cross-compiler package do not only allow _installing_ the Qt modules separately, but also _building_ them separately. And I have already updated all modules to 5.7.0, except WebKit because I'm still unable to resolve the build issues. The cause of the problem might be that Arch updated mingw-w64-gcc to version 6.1 which behaves differently when the -isystem flag is used or that there are some changes in qmake 5.7.0 causing the issues. I don't believe that changes in the WebKit module itself are the problem because compared to the 5.6.1 version I didn't notice any relevant changes.

To the ANGLE thing: I had to put some effort in it to make it working. Needed to patch ANGLE itself, qt-base and of course the WebKit module. Some time ago I committed some of the changes here, too. But I don't know whether it is actually working here. But _not_ to use ANGLE should be the less error prone way, anyways.

**Comment by mcallegari** [comment] 2016-06-25 15:36
@Martchus you mentioned that you have built all the 5.7.0 modules. Can you please check the "controls" example of the Qt3D module and tell me if it works for you ?
My qt5-git build of 5.7.0 produces a white empty window when I launch it. Can't figure out why, since all the other examples (minus another one) work perfectly.
I suspect there is some sort of error in the qmake qml plugins path resolution, but it's really weird cause it should affect many examples. Instead just very few of them have this issue.

**Comment by mcallegari** [comment] 2016-06-25 18:27
All sorted ! :tada: 
see #1507

**Comment by Martchus** [comment] 2016-06-25 19:01
Yet another patch :-) But I think I'll also add the patch to my packages since the bug seems critical enough.

**Comment by mcallegari** [comment] 2016-06-29 07:02
Just a quick update. I reported what I found here
https://bugreports.qt.io/browse/QTBUG-54346
and a patch has been submitted to be merged
https://codereview.qt-project.org/#/c/163566/

I haven't tested it yet, but at least it's good sometimes they care about MSYS2...

**Comment by nickdiego** [comment] 2016-08-19 21:15
Hello, I getting "white screens" (not sure are the same @mcallegari got, as he described here) when trying to run Qt Quick app built using MSYS2 Qt5 package. The terminal output shows some OpenGL errors. I'm using a Windows 8.1 installed in VirtualBox environment, no additional video drivers installed (it used Microsoft ones, which supports OpenGL 1.1), so I'm quite sure the errors happens because Qt5  for MSYS2 are configured/built/packaged with "-opengl=desktop" instead of "angle" or "dynamic".
Just opened #1649 to keep tracking of adding support to "angle" or "dynamic" to qt5 packages, before to open it I searched for something similar and didn't found, I'm sorry if it already exists somewhere.
Thanks, and if necessary I'd be happy to helping on that.

**Comment by asampal** [comment] 2016-12-15 06:41
Is this package close to being released?

**Comment by lazka** [comment] 2018-08-07 06:42
Anything more to do here? We are at 5.11.1 now.

**Comment by mcallegari** [comment] 2018-08-07 09:18
This can be closed.

**Comment by lazka** [comment] 2018-08-07 09:31
@mcallegari thanks

**Closed by lazka** 2018-08-07 09:31 UTC
Labels: needinfo
