### ISSUE TITLE
appveyor: python related build failure

### ISSUE THREAD

**Issue by filnet** [Alexpux/MINGW-packages#3494] opened 2018-03-17 15:09 UTC
See https://github.com/Alexpux/MINGW-packages/pull/3491#issuecomment-373771058

```
[ 86%] Building CXX object python/CMakeFiles/vrpn-python.dir/Base.cpp.obj
In file included from C:/msys64/mingw32/include/c++/7.3.0/math.h:36:0,
                 from C:/Python36-x64/include/pyport.h:194,
                 from C:/Python36-x64/include/Python.h:50,
                 from C:/M/mingw-w64-vrpn/src/vrpn-07.34/python/include/Base.hpp:4,
                 from C:/M/mingw-w64-vrpn/src/vrpn-07.34/python/Base.cpp:1:
C:/msys64/mingw32/include/c++/7.3.0/cmath:1136:11: error: '::hypot' has not been declared
   using ::hypot;
           ^~~~~
make[2]: *** [python/CMakeFiles/vrpn-python.dir/build.make:63: python/CMakeFiles/vrpn-python.dir/Base.cpp.obj] Error 1
```

Not sure it is related to appveyor picking up C:/Python36-x64 when building on mingw32...

**Comment by mati865** [comment] 2018-03-17 18:08
If it's caused by picking wrong Python then https://github.com/Alexpux/MINGW-packages/pull/3493 would fix it.

**Comment by lazka** [comment] 2018-03-18 08:28
Yeah, your error made me open the PR, but not sure if it helps.. :)

**Comment by filnet** [comment] 2018-03-18 09:50
@lazka on the breach as usual :)

I'll wait for your PR to be merged and will trigger a new build of mine.

@Alexpux ^

**Comment by lazka** [comment] 2018-05-15 05:19
> @lazka on the breach as usual :)
> 
> I'll wait for your PR to be merged and will trigger a new build of mine.

it got merged

**Comment by filnet** [comment] 2018-05-15 11:03
test in progress...

While looking at the 32 bit appveyor build log, I noticed that both i686 and x86_64 packages are downloaded and upgraded:

```
upgrading mingw-w64-i686-openssl...
upgrading mingw-w64-i686-xz...
upgrading mingw-w64-i686-sqlite3...
upgrading mingw-w64-i686-python3...
upgrading mingw-w64-x86_64-libiconv...
upgrading mingw-w64-x86_64-gcc-libs...
upgrading mingw-w64-x86_64-binutils...
upgrading mingw-w64-x86_64-headers-git.
```

Any reasons ?

**Comment by filnet** [comment] 2018-05-15 11:07
Build success none the less +1

**Comment by lazka** [comment] 2018-05-15 11:53
> Any reasons ?

The initial system upgrade updates all packages installed by appveyor by default. pacman doesn't allow limiting that to a specific repo afaik.

**Closed** 2018-05-15 11:56 UTC
