### ISSUE TITLE
mingw-w64-x86_64-lldb doens't package lldb-server

### ISSUE THREAD

**Issue by russelltg** [Alexpux/MINGW-packages#2283] opened 2017-03-11 04:14 UTC
For libraries linking with lldb, lldb-server must be packaged, yet it isn't.

**Comment by mati865** [comment] 2017-03-11 15:28
Duplicate of https://github.com/Alexpux/MINGW-packages/issues/1941

It is upstream issue as `lldb-server`depends on POSIX.

**Closed** 2018-10-02 05:09 UTC
