### ISSUE TITLE
fontconfig.pc doesn't define prefix

### ISSUE THREAD

**Issue by RyanGlScott** [Alexpux/MINGW-packages#872] opened 2015-11-09 17:30 UTC
This is half-bug-report, half-question (since I'm not sure which label describes it best). I'm trying to install a Haskell package ([`cairo`](http://hackage.haskell.org/package/cairo)) that depends on `mingw-w64-x86_64-cairo` being installed. However, it doesn't work out-of-the-box at the moment. You can read the full error log [here](https://github.com/gtk2hs/gtk2hs/issues/139), but the gist of it is that a Windows tool (`ghc-pkg`) is being confused by a Unix-style paths (e.g., `/mingw64/include/freetype2` rather than, say, `C:/msys2/mingw64/include/freetype2`).

The issue seems to be related to `fontconfig.pc` (since `fontconfig` is one of `cairo`'s dependencies). If you run `pkg-config --cflags fontconfig`, you get some interesting results:

```
-mms-bitfields -IC:/msys64/mingw64/include -I/mingw64/include/freetype2 -I/mingw64/include/libpng16 -I/mingw64/include/harfbuzz -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include
```

There are many duplicates that have only changed `-IC:/msys64/mingw64/...` to `-I/mingw64/...`. The latter kind of paths are probably what is confusing `ghc-pkg`.

Curiously, this seems to be intentional, since there is a [`.patch` file](https://github.com/Alexpux/MINGW-packages/blob/6bbd4c6257dd3cf6118e62288c256825aac7b02c/mingw-w64-fontconfig/0007-pkgconfig.mingw.patch) that configures this behavior via `--dont-define-prefix`:

```patch
--- fontconfig-2.11.93/m4/pkg.m4.orig	2015-03-09 02:54:03.000000000 +0000
+++ fontconfig-2.11.93/m4/pkg.m4	2015-04-06 11:04:21.862416100 +0000
@@ -111,8 +111,8 @@
 pkg_failed=no
 AC_MSG_CHECKING([for $1])
 
-_PKG_CONFIG([$1][_CFLAGS], [cflags], [$2])
-_PKG_CONFIG([$1][_LIBS], [libs], [$2])
+_PKG_CONFIG([$1][_CFLAGS], [cflags --dont-define-prefix], [$2])
+_PKG_CONFIG([$1][_LIBS], [libs --dont-define-prefix], [$2])
 
 m4_define([_PKG_TEXT], [Alternatively, you may set the environment variables $1[]_CFLAGS
 and $1[]_LIBS to avoid the need to call pkg-config.
@@ -207,7 +207,7 @@
 [AC_REQUIRE([PKG_PROG_PKG_CONFIG])dnl
 AC_ARG_VAR([$1], [value of $3 for $2, overriding pkg-config])dnl
 
-_PKG_CONFIG([$1], [variable="][$3]["], [$2])
+_PKG_CONFIG([$1], [variable="][$3][" --dont-define-prefix], [$2])
 AS_VAR_COPY([$1], [pkg_cv_][$1])
 
 AS_VAR_IF([$1], [""], [$5], [$4])dnl
```

My question is: if this was not intentional, could this be removed to make building `cairo` easier? And if it _is_ intentional, can you give me an explanation for why it is done that way?

**Comment by Alexpux** [comment] 2015-11-09 18:25
This patch cannot be removed because this solve problems with building/installing programs using right UNIX paths instead hardcoding full Windows paths.

**Comment by Alexpux** [comment] 2015-11-09 18:38
Also seems you use wrong **pkg-config**. I can't reproduce this isuue with pkg-config from mingw package.
````
$ pkg-config --cflags freetype2
-mms-bitfields -ID:/develop/msys64/mingw64/include/freetype2 -ID:/develop/msys64/mingw64/include -ID:/develop/msys64/mingw64/include/libpng16 -ID:/develop/msys64/mingw64/include/harfbuzz -ID:/develop/msys64/mingw64/include/glib-2.0 -ID:/develop/msys64/mingw64/lib/glib-2.0/include
````

**Comment by RyanGlScott** [comment] 2015-11-09 18:41
Are we talking about the same thing? I'm looking at the flags for `fontconfig`, not `freetype2`:

```bash
$ pkg-config --cflags fontconfig
-mms-bitfields -IC:/msys64/mingw64/include -I/mingw64/include/freetype2 -I/mingw64/include/libpng16 -I/mingw64/include/harfbuzz -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include

$ which pkg-config
/mingw64/bin/pkg-config
```

**Comment by Alexpux** [comment] 2015-11-09 18:42
Ah sorry I'm missreasding:)

**Comment by Alexpux** [comment] 2015-11-09 18:43
But in anyway we can't remove pkg-config patch. Need to solve this in different way

**Comment by Alexpux** [comment] 2015-11-09 18:45
If you look into fontconfig.pc file then you can see that not converted paths are hardcoded in Cflags.

**Comment by Alexpux** [comment] 2015-11-09 18:47
So from my point of view this is **pkg-config** issue because it not delete parts of CFLAGS after convert.

**Comment by RyanGlScott** [comment] 2015-11-09 18:48
You're referring to this line in `fontconfig.pc`, right?

```
Cflags: -I${includedir}  -mms-bitfields -I/mingw64/include/freetype2 -I/mingw64/include/libpng16 -I/mingw64/include/harfbuzz -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include  -I/mingw64/include
```

It does appear that they are hardcoded paths, which makes dealing with this tricky. Would the only solution here be running MSYS's `cygpath` before passing them to `ghc-pkg`? Or is there some way to configure `pkg-config` to output those paths differently?

**Comment by Alexpux** [comment] 2015-11-09 18:53
Yeah. I'm about this line.
I think this issue need to be reported upstream to pkg-config devs. 
They need remove parts during convert.
Output:
````
-mms-bitfields -IC:/msys64/mingw64/include 
**1** -I/mingw64/include/freetype2 -I/mingw64/include/libpng16 -I/mingw64/include/harfbuzz -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include 
**2** -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/harfbuzz -IC:/msys64/mingw64/include/glib-2.0 -IC:/msys64/mingw64/lib/glib-2.0/include
````
2 is converted 1. So during convert  1 need to be removed.

**Comment by RyanGlScott** [comment] 2015-11-09 19:26
OK, this does seem like a `pkg-config`-related bug. I'm a bit unclear on what your proposed solution is, however. Are you proposing that when `pkg-config` reads a path like `-I/mingw64/include/freetype2` from a `.pc` file, it shouldn't output it? Or are you proposing something else?

**Comment by Alexpux** [comment] 2015-11-09 19:54
When pkg-config convert UNIX-like path to Windows form it need remove unix path from output

**Comment by dbnicholson** [comment] 2015-11-09 23:40
So, pkg-config doesn't really do Windows style conversion itself. There's a couple nasty hacks to try to make Windows work better.

1. On initialization, `pkg-config` uses `g_win32_get_package_installation_directory_of_module` to construct the list of paths to look for `.pc` files in. This in turn uses `GetModuleFileNameW` to get the Windows style path of the running `pkg-config` process. In the standard case where you just provide a package name on the command line, they'll be found from this search path and the internal path of the `.pc` file will be in Windows format.

2. When reading out `.pc` files on Windows (by default), the `${prefix}` variable will be substituted with the grandparent directory of the file. This does depend on people constructing the `.pc` files in a nice way. This can be toggled at runtime by passing the `--define-prefix`/`--dont-define-prefix` options.

That's a terrible hack, but it was requested by Windows folks since the fixed paths included in the files don't typically match Windows development style. There's no actual conversion of the paths besides this.

Now, you could say that the paths should just be converted to Windows style all the time. But I don't know of any way to do that on mingw or msys. On cygwin, you at least get some conversion functions (https://cygwin.com/cygwin-api/func-cygwin-conv-path.html), but I'm not aware of any such API on mingw or msys. I don't even know the correct way to detect if we're running under mingw or msys. And judging by the discussion above, it's not really clear whether Unix or Windows style paths should be used in mingw/msys.

**Comment by RyanGlScott** [comment] 2015-11-10 17:55
`sys/cygwin.h` is also available in MSYS2 via the `msys2-runtime-devel` package. (You can also get in MSYS via the `msys-core` package, but it's a very outdated version of `sys/cygwin.h` that doesn't support Unicode, AFAICT.)

As far as detecting Cygwin/MSYS2, here is what I know (MSYS2 devs, please chime in if there are better ways to do this):

1. The Cygwin `gcc` port defines `__CYGWIN__`, and the MSYS2 `gcc` port defines `__MSYS__`.
2. In `autoconf`, the `AC_CANONICAL` macros tell you whether you are running Cygwin or MinGW. Here's [an example](https://github.com/mongodb/mongo-c-driver/blob/df4d1f31eca0a08510c5185bfb488dbd4f108b6e/build/autotools/CheckHost.m4#L8) of it in action.
3. `uname -s` should tell you if you're on `CYGWIN*` or `MINGW*`.
4. The `$OSTYPE` environmental variable should tell you if you're on `cygwin` or `msys`.

**Comment by Alexpux** [comment] 2015-11-10 18:00
1. MSYS2 gcc define both ````__CYGWIN__```` and ````__MSYS__````
2. Add there ````*-*-msys*```` too
3. Under MSYS2 shell ````uname -s```` return to you ````MSYS*````
4. ok

**Comment by RyanGlScott** [comment] 2016-01-20 16:16
@dbnicholson, I'd like to try and fix whatever needs to be fixed with `pkg-config`, but I'm not familiar with all of the places in the `pkg-config` source code where it reads in filepaths. If you could point out where they live, I could take a shot at converting them to Windows-style paths (whenever `autoconf` detects Cygwin or MSYS is being used.)

**Comment by mingwandroid** [comment] 2016-01-20 18:15
You can't know what the nature of the final consumer-compiler will be though.

Any of Autotools, CMake, GYP, SCons, Qbs etc could all call `pkg-config`. You could try to figure out whether they were MinGW-w64 variants of msys2 variants (e.g. we have both for cmake) and then assume the same will be true of the compiler, so assume that msys2 cmake will call msys2 GCC), now that may be true or it may not!

Maybe better would be to declare it upfront with an MSYS2_ env. var. which is our traditional approach to working around MSYS2 oddities.

Your thoughts please.

**Comment by dbnicholson** [comment] 2016-01-20 19:25
Yeah, this is all pretty hairy considering how loosely the msys/mingw platform is defined. Some thoughts:

* Currently pkg-config determines if you're on "native" win32 by detecting mingw in the host triplet - http://cgit.freedesktop.org/pkg-config/tree/configure.ac#n159. This is to distinguish it from cygwin where standard Unix style paths and lookups work normally. I suppose it could add the `*-*-msys*` as mentioned above.

* Within the code, though, the preprocessor directive used is `G_OS_WIN32`, which is defined by glib. That in turn is defined by glib's configure for the `*-*-mingw*` triplet. So, `native_win32` and `G_OS_WIN32` are basically identical. That code is at http://cgit.freedesktop.org/pkg-config/tree/glib/configure.ac#n3215 and looks to be the same in upstream glib. So, I don't think catching `*-*-msys*` will work here.

* Probably this will need some type of runtime detection. Correct me if I'm wrong, but people would likely take a `pkg-config` compiled in an MSYS environment and expect it to work under a non-MSYS environment like the normal Windows shell, right?

* I still honestly don't understand the differences between the MinGW and MSYS environments. Is one a subset of the other? Do they expect Windows style paths of Unix style paths?

* I think a path conversion utility function will likely need to be copied into pkg-config. We can't depend on cygwin to be there at runtime. Unless I'm missing something and the MinGW/MSYS compiler provides some statically linked in convenience functions.

* I believe that any conversion would likely have to happen with the `parse_line()` function - http://cgit.freedesktop.org/pkg-config/tree/parse.c#n903. No guarantees, though.

**Comment by RyanGlScott** [comment] 2016-01-21 01:48
> I still honestly don't understand the differences between the MinGW and MSYS environments. Is one a subset of the other? Do they expect Windows style paths of Unix style paths?

They're "environments", but with two different definitions of the word "environment". MinGW(-w64) is an development environment in the sense that it is a collection of software intended for developing native Windows applications. MSYS(2) is a Unix-like shell environment which uses its own runtime.

To illustrate the difference, there are actually two `pkg-config`s you can install with MSYS2: `mingw-w64-x86_64-pkg-config` and `pkg-config`. `mingw-w64-x86_64-pkg-config` (the MinGW-w64 version) is a fully native Windows application that you can run anywhere. `pkg-config` (the MSYS2 version) needs to be run from within the MSYS2 shell, IIRC.

Having said that, that makes me realize...

> I think a path conversion utility function will likely need to be copied into pkg-config. We can't depend on cygwin to be there at runtime. Unless I'm missing something and the MinGW/MSYS compiler provides some statically linked in convenience functions.

...that my [earlier suggestion](https://github.com/Alexpux/MINGW-packages/issues/872#issuecomment-155513526) above is bogus. There's no way `mingw-w64-x86_64-pkg-config` can depend on `msys2-runtime-devel`, since that would lock it into MSYS2, which is precisely what I don't want to happen. So I don't think we can use `sys/cygwin.h` at all here.

@mingwandroid, can you elaborate more on "declare it upfront with an MSYS2_ env. var"? Could one reliably figure out the right path manipulation based on the definition of, say, `$OSTYPE`?

**Comment by mingwandroid** [comment] 2016-01-21 09:16
Please read the MSYS2 wiki: sourceforge.net/p/msys2/wiki/

**Comment by RyanGlScott** [comment] 2016-01-21 22:21
@mingwandroid, thanks for the link. The [Hard-coded paths and relocation](http://sourceforge.net/p/msys2/wiki/Porting/#hard-coded-paths-and-relocation) section has an interesting nugget of wisdom:

> Sometimes these paths are baked into shell scripts or pkg-config's `.pc` files. In that case, you should use `sed` in the `PKGBUILD package()` function to correct this back to the `msys2` version of the path.

Interestingly, the the `PKGBUILD package()` function for `mingw-w64-fontconfig` [does _not_ use `sed`](https://github.com/Alexpux/MINGW-packages/blob/44314372fe0976f77c02c124b458be6865042f78/mingw-w64-fontconfig/PKGBUILD#L66) at the moment to sanitize `fontconfig.pc`'s hardcoded paths. Is there any reason it couldn't? Perhaps that would be an easier fix than changing the source code of `pkg-config` itself.

**Closed** 2016-02-15 13:27 UTC
