### ISSUE TITLE
clang++-3.7.0 and libc++

### ISSUE THREAD

**Issue by vpetrigo** [Alexpux/MINGW-packages#771] opened 2015-09-03 05:24 UTC
Hello,

I have met an issue with building proogram via clang++ with libc++.
I installed the **mingw-w64-x86_64-clang 3.7.0-1** package and also **mingw-w64-x86_64-libc++ 3.7.0-1** and **mingw-w64-x86_64-libc++abi 3.7.0-1**.
After that I tried to compile the code below with that command `clang++ -stdlib=libc++ hello.cpp -o hello -nodefaultlibs -std=c++14 -lc++ -lc++abi -lm -lgcc_s -lgcc`:

``` cpp
#include <iostream>                

int main() {                       
    std::cout << "Hello, World!\n";

    return 0;                      
}                                  
```

However, the output is dozens of undefined references:

```
C:\msys64\mingw64\x86_64-w64-mingw32\lib\crt2.o: In function `pre_c_init':
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:130: undefined reference to `__set_app_type'
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:133: undefined reference to `_encode_pointer'
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:141: undefined reference to `_setargv'
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:132: undefined reference to `__set_app_type'
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:145: undefined reference to `_matherr'
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:145: undefined reference to `__mingw_setusermatherr'
C:\msys64\mingw64\x86_64-w64-mingw32\lib\crt2.o: In function `pre_cpp_init':
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:162: undefined reference to `__getmainargs'
C:\msys64\mingw64\x86_64-w64-mingw32\lib\crt2.o: In function `__tmainCRTStartup':
C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:254: undefined reference to `__imp_Sleep'
...
```

What might it be?

**Comment by martell** [comment] 2015-09-03 06:02
Hey :)

You are linking with -nodefaultlibs
So you are missing all the libs crtexe.c needs such as libmingwex.

You will have to look up what libraries the functions belong to
example:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686298(v=vs.85).aspx
Thus __imp_Sleep is in libkernel32

building a simple hello world with clang -v will show you whats missing

**Comment by vpetrigo** [comment] 2015-09-03 06:21
@martell it was the last option I tried from **libc++** main page. Anyway, here is the log with `-###` option:
```
clang version 3.7.0 (tags/RELEASE_370/final)
Target: x86_64-w64-windows-gnu
Thread model: posix
 "C:\\msys64\\mingw64\\bin\\clang++.exe" "-cc1" "-triple" "x86_64-w64-windows-gnu" "-emit-obj" 
"-mrelax-all" "-disable-free" "-disable-llvm-verifier" "-main-file-name" "hello.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-fmath-errno" "-masm-verbose" 
"-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-momit-leaf-frame-pointer" "-dwarf-column-info" "-resource-dir" "C:\\msys64\\mingw64\\bin\\..\\lib\\clang\\3.7.0" "-internal-isystem" 
"C:\\msys64\\mingw64\\include\\c++\\v1" "-internal-isystem" 
"C:\\msys64\\mingw64\\bin\\..\\lib\\clang\\3.7.0\\include" "-internal-isystem" 
"C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0\\include" "-internal-isystem" 
"C:\\msys64\\mingw64\\x86_64-w64-mingw32/sys-root/mingw/include" "-internal-isystem" 
"C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0\\include-fixed" "-internal-isystem" "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\include" "-internal-isystem" "C:\\msys64\\mingw64\\include" "-std=c++14" "-fdeprecated-macro" "-fdebug-compilation-dir" "C:\\Users\\pve\\Dropbox\\Work\\Stroustrup\\section20" "-ferror-limit" "19" "-fmessage-length" "151" 
"-mstackrealign" "-fno-use-cxa-atexit" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fdiagnostics-show-option" "-fcolor-diagnostics" "-o" "C:\\msys64\\tmp\\hello-439e72.o" "-x" "c++" "hello.cpp"
 "C:\\msys64\\mingw64\\bin\\ld.exe" "-m" "i386pep" "-Bdynamic" "-o" "hello" 
"C:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib\\crt2.o" "C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0\\crtbegin.o" "-LC:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0" 
"-LC:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib" "-LC:\\msys64\\mingw64\\lib" 
"-LC:\\msys64\\mingw64\\x86_64-w64-mingw32/sys-root/mingw/lib" "C:\\msys64\\tmp\\hello-439e72.o" "-lc++" "-lc++abi" "-lm" "-lgcc_s" "-lgcc" "-lc++" "-lmingw32" "-lgcc_s" "-lgcc" "-lmoldname" "-lmingwex" "-lmsvcrt" "-ladvapi32" "-lshell32" "-luser32" "-lkernel32" "-lmingw32" "-lgcc_s" "-lgcc" "-lmoldname" "-lmingwex" "-lmsvcrt" "C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0\\crtend.o"
```
As you can see all necessary libraries seem to be linked with my test program.

**Comment by martell** [comment] 2015-09-03 06:42
hmm -nodefault libs implies otherwise as the driver code in clang I wrote should not link these when that is passed.

I think for mingw-w64 we will have to build a shared libc++ so that we don't depend on libc++abi.
But the error you are getting is in no way related to libc++ specifically.

You should be able compare the differences between using libstdc++ and libc++ and reproduce the issue or at least compare the different arguments to see what is causing this.

Using a static libstdc++ would be ideal for tracking this bug down.

**Comment by vpetrigo** [comment] 2015-09-03 07:12
@martell ok, I'll try to do that.

**Comment by martell** [comment] 2015-09-03 07:21
Great :)
Ideally you should be able to just pass -stdlib=libc++ and it should work.
Because it is static however we need to get libc++abi into the args somehow.
I will work on getting a shared libc++ as soon as i get back.

You can call -c on clang to just compile the object for you without linking.
Then you can manually invoke the linker replacing every occurrence of "lc++" with "lc++ -lc++abi" in the linker args to track down your bug.

**Comment by vpetrigo** [comment] 2015-09-03 08:29
Linker part of building with `libc++` doesn't deffer from `libstdc++` or better to say changes only in one parameter `-lc++` instead of `-lstdc++`. I tried to invoke only `ld` command for my object file like that:
```
"C:\\msys64\\mingw64\\bin\\ld.exe" -m i386pep -Bdynamic -o hello.exe "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib\\crt2.o" "C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0\\crtbegin.o" "-LC:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0" "-LC:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib" "-LC:\\msys64\\mingw64\\lib" "-LC:\\msys64\\mingw64\\x86_64-w64-mingw32/sys-root/mingw/lib" "hello.o" -lc++ -lc++abi -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt "C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0\\crtend.o"
```
But it throws me lots of undefined references in the `ios.cpp.obj`, `locale.cpp.obj`, `iostream.cpp.obj` and so on.
I'm going to go further, here is the temporary result.

**Comment by ncihnegn** [comment] 2015-09-04 08:23
ld -o test test.o -lc++ -lc++abi -lpthread -lstdc++ -lgcc_s -lgcc -lmingw32 -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -L /mingw64/lib/gcc/x86_64-w64-mingw32/5.2.0/ -L /mingw64/x86_64-w64-mingw32/lib
locale.cpp.obj is the biggest issue.
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text$_ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_baseES4_[_ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_baseES4_]+0x0): multiple definition of `std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char)'
test.o:(.text[_ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_baseES4_]+0x0): first defined here
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text+0x2bb7): undefined reference to `_free_locale'
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text+0x2bf7): undefined reference to `_free_locale'
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text+0x2c37): undefined reference to `_free_locale'
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text+0x2c77): undefined reference to `_free_locale'
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text+0x2cb7): undefined reference to `_free_locale'
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text+0x2cf7): more undefined references to `_free_locale' follow
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text+0x3750): undefined reference to `btowc_l(int, localeinfo_struct*)'
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text+0x3782): undefined reference to `wctob_l(unsigned short, localeinfo_struct*)'
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text+0x37c9): undefined reference to `wctob_l(unsigned short, localeinfo_struct*)'
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text+0x38b1): undefined reference to `wcsnrtombs_l(char*, wchar_t const**, unsigned long long, unsigned long long, int*, localeinfo_struct*)'
c:\tools\msys64\mingw64\bin\../../mingw64/lib/libc++.a(locale.cpp.obj):(.text+0x38f8): undefined reference to `wcrtomb_l(char*, wchar_t, int*, localeinfo_struct*)'
.......

**Comment by ncihnegn** [comment] 2015-09-04 08:27
And the link order is deadly wrong. It puts -lc++abi before -lc++.
clang++ -stdlib=libc++ test.cpp -o test -lc++abi -v
 "C:\\tools\\msys64\\mingw64\\bin\\ld.exe" -m i386pep -Bdynamic -o test "C:\\tools\\msys64\\mingw64\\x86_64-w64-mingw32\\lib\\crt2.o" "C:\\tools\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0\\crtbegin.o" "-LC:\\tools\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0" "-LC:\\tools\\msys64\\mingw64\\x86_64-w64-mingw32\\lib" "-LC:\\tools\\msys64\\mingw64\\lib" "-LC:\\tools\\msys64\\mingw64\\x86_64-w64-mingw32/sys-root/mingw/lib" "C:\\tools\\msys64\\tmp\\test-d44fa1.o" -lc++abi -lc++ -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt "C:\\tools\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0\\crtend.o"

**Comment by vpetrigo** [comment] 2015-09-04 12:30
@ncihnegn  you can compile and then link with the command below:
```
ld hello.o -o hello.exe "C:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib\\crt2.o" "C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0\\crtbegin.o" "-LC:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0" "-LC:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib" "-LC:\\msys64\\mingw64\\lib" "-LC:\\msys64\\mingw64\\x86_64-w64-mingw32/sys-root/mingw/lib" "hello.o" -lc++ -lc++abi -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt "C:\\msys64\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\5.2.0\\crtend.o"
```
But anyway there are lots of undefined references. :cry:

**Comment by m-j-w** [comment] 2015-11-05 06:17
With respect to the missing locale functions, it seems like the cpp files in `libcxx/src/support/win32/` are not being compiled into `libc++.a` or `libc++abi.a`. The two files are accordingly `locale_win32.cpp` and `support.cpp`. An `nm -A libc++* | grep locale_win32` is just empty. I found those files and the required symbols in https://github.com/llvm-mirror/libcxx/tree/master/src/support/win32

Other than that, and besides the switched order of `-lc++` and `-lc++abi`, it also appears that `-lpthread` and C++ memory allocation functions (like operator new, delete) and exceptions are missing. Threads are required since gcc is compiled with posix threads, and would be automatically added with the `-pthread` flag. For exceptions (`__gxx_personality_seh0`) and allocation functions simply adding `-lstdc++` directly after `-lc++abi` at least removes the symbol lookup failure, but, presumably, that is not how it is intended to be.

**Comment by rpavlik** [comment] 2016-04-21 20:46
Some of this might be related to #213?

**Comment by martell** [comment] 2016-06-11 06:59
Hi Sorry I haven't been around for awhile.
Fixed cmake so the local_win32 is compiled and support.
Applied a patch on top to not provide the functions mingw-w64 already has for these.

Narrowed it down to this 4 missing symbols. 
```
libc++.a(locale.cpp.obj): undefined symbol: _free_locale
libc++.a(locale.cpp.obj): undefined symbol: __imp__strftime_l
libc++.a(locale_win32.cpp.obj): undefined symbol: _create_locale
libc++.a(locale_win32.cpp.obj): undefined symbol: _get_current_locale
```

linking with msvcr100 instead of msvcrt fixes this but I think we will have to upstream an implementation of these into libmingwex or libmingw32, or wherever the correct location for them is.

Anyway here is c++ working with clang and compiler-rt and libc++ in all its glory :)
https://gist.github.com/martell/0610948571084f6b097314af029f63ee

**Comment by ncihnegn** [comment] 2016-06-11 09:34
@martell Could you please share the patch?

**Comment by mingwandroid** [comment] 2016-06-11 16:29
Hello @martell, good to hear from you again. And good work on clang!

**Comment by martell** [comment] 2016-06-11 23:59
Hi @ncihnegn, I am not even using libstdc++ or libsupr++ to bootstrap it so my build won't be of much use.
I will share the locale fix though with the stubs for the 4 missing functions.
Will land that in mingw-packages

Hi @Alexpux, @mingwandroid I successfully built a shared version by cross compiling from OSX/linux to windows the issue I have now is that the shared version is being created as libc++.so instead of libc++.dll
The other file is libc++.dll.a which is correct. It is a valid dll but the name is just wrong

**Comment by DJviolin** [comment] 2017-01-25 21:12
I think my problem is related here. Pastebin: http://pastebin.com/5tdqUBLP

I try to compile with this command:

```sh
clang++ -v -std=c++1z -stdlib=libc++ -g -Weverything -Werror -Wno-c++98-compat -Wno-c++98-compat-pedantic -Ofast -march=native -ffast-math src/013_find_repeated_words.cpp -o bin/013_find_repeated_words
```

**Comment by EricWF** [comment] 2017-05-11 05:54
I'm currently fixing this in Libc++. Commenting so I'm on the CC list for this bug.

**Comment by EricWF** [comment] 2017-05-11 05:57
> Linking with msvcr100 instead of msvcrt fixes this but I think we will have to upstream an implementation of these into libmingwex or libmingw32, or wherever the correct location for them is.

@martell Has any progress been made on this? I set up a buildbot for Libc++ that tests MinGW and I'm just trying to figure out how to avoid this.

**Comment by mati865** [comment] 2017-05-11 08:30
@EricWF I've partially succeed using msvcrt and libsupc++. One have to add `-lsupc++` to the Clang command and it failed with `undefined reference to '__imp___cxa_call_unexpected'` anyway.
I wanted to add MinGW based compiler to Libc++ buildbot but couldn't find time for it.

Right now GCC is the best way to build static Libc++ (shared version is broken) due to http://lists.llvm.org/pipermail/cfe-dev/2017-April/053530.html and other Clang issues with MinGW-w64.

I commited my unfinished patches (lack of time again) here https://github.com/mati865/MINGW-packages/commit/c86a8f05ac7670683c7bcc841183518aba6e108f#diff-d24cec22e30d4aafe9264b56892a8d18R37
Use what do you want from them and if you have any questions you can add inline comments on my commit.
I'll test and review https://reviews.llvm.org/D33082 over the weekend.

**Comment by EricWF** [comment] 2017-05-11 08:36
> I wanted to add MinGW based compiler to Libc++ buildbot but couldn't find time for it.

https://ci.appveyor.com/project/llvm-mirror/libcxx

I set it up yesterday. After applying https://reviews.llvm.org/D33082 I have Libc++ building, and I'm sitting on patches that get it closer to linking. (See https://ci.appveyor.com/project/EricWF/libcxx-5skm5/build/job/4be2xcshqlitgs0w)

@mati865 I found your patches via Google, they were a huge help. Thank you. Hopefully MinGW-w64 won't need to maintain downstream fixes anymore :-)

**Comment by mati865** [comment] 2017-05-11 08:53
@EricWF you probably found old version of them (maybe even those created by @martell). I'm glad they were usefull.

**Comment by martell** [comment] 2017-05-11 10:15
I will reply and give a general update here seen as many want this.

I have had libc++ building for mingw-w64 for awhile but with compiler-rt and lld, not gcc and binutils so I would not be of much help here.
I specifically avoid patches that link to libgcc and gcc_eh.

compnerd has updated libc++ to build as standalone for msvc in recent months so we should be able to take advantage of that. This is most likely why your libc++ is in much better shape now.

LLD has had a regression upstream with linking mingw-w64 programs because of this change so I haven't had a chance to test out the new libc++ support.

I have already bootstrapped mingw-w64-clang with mingw-w64-clang as the build host.

Your message prompted me to ask about getting that lld regression resolved.
http://lists.llvm.org/pipermail/llvm-dev/2017-May/112937.html

Also I have a bunch of patches merged upstream and in review.
I just takes time to get some things in tree.
https://reviews.llvm.org/D32689
https://reviews.llvm.org/rL300562
https://reviews.llvm.org/rL300555

**Comment by martell** [comment] 2017-05-11 12:18
> Has any progress been made on this? I set up a buildbot for Libc++ that tests MinGW and I'm just trying to figure out how to avoid this.
@EricWF I haven't had a chance to deal with writing and upstreaming these.
This might be of some help though
https://github.com/martell/mingw-w64-clang/blob/master/patches/libcxx/0001-mingw-w64-hack-and-slash-fixes-for-libc.patch

**Comment by martell** [comment] 2017-05-11 12:46
To keep some level of tracking in this thread I just created.
https://reviews.llvm.org/D33098
To build on top of EricWF's changes

**Comment by martell** [comment] 2017-05-21 13:07
Hey @EricWF I had an hour today while waiting on work related stuff to build.
So I followed up with another patch to cleanup some things for bootstrapping.
https://reviews.llvm.org/D33384

Here is the last error I have with libcxxabi
Would you be able to give any insight as to why there is a duplicate?

```
-- Build files have been written to: /Users/martell/dev/contract/build-libcxxabi-x86_64-git
[18/19] Linking CXX shared library src/libc++abi.dll
FAILED: src/libc++abi.dll lib/libc++abi.dll.a
: && /Users/martell/llvm/usr/bin/x86_64-w64-mingw32-clang++  -Wa,-mbig-obj -Werror=date-time -std=gnu++11 -w --target=x86_64-w64-mingw32 -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -std=c++11 -fstrict-aliasing -fno-exceptions  --target=x86_64-w64-mingw32 -rtlib=compiler-rt -nodefaultlibs -shared -o src/libc++abi.dll -Wl,--out-implib,lib/libc++abi.dll.a -Wl,--major-image-version,1,--minor-image-version,0 src/CMake
Files/cxxabi_objects.dir/cxa_aux_runtime.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_default_handlers.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_demangle.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_exception_storage.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_guard.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_handlers.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_unexpected.cpp.obj src/CMakeFiles/
cxxabi_objects.dir/cxa_vector.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_virtual.cpp.obj src/CMakeFiles/cxxabi_objects.dir/stdlib_exception.cpp.obj src/CMakeFiles/cxxabi_objects.dir/stdlib_stdexcept.cpp.obj src/CMakeFiles/cxxabi_objects.dir/stdlib_typeinfo.cpp.obj src/CMakeFiles/cxxabi_objects.dir/abort_message.cpp.obj src/CMakeFiles/cxxabi_objects.dir/fallback_malloc.cpp.obj src/CMakeFiles/cxxabi_object
s.dir/private_typeinfo.cpp.obj src/CMakeFiles/cxxabi_objects.dir/stdlib_new_delete.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_noexception.cpp.obj  -lmingw32 /Users/martell/llvm/usr/lib/clang/5.0.0/lib/windows/libclang_rt.builtins-x86_64.a -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 /Users/martell/llvm/usr/lib/clang/5.0.0/lib/windows/libclang_rt.builtins-x86_64.a -lmol
dname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && :
/Users/martell/llvm/usr/bin/lld: error: duplicate symbol: _ZTISt9exception in src/cmakefiles/cxxabi_objects.dir/cxa_default_handlers.cpp.obj and in src/cmakefiles/cxxabi_objects.dir/stdlib_exception.cpp.obj
/Users/martell/llvm/usr/bin/lld: error: duplicate symbol: _ZTSSt9exception in src/cmakefiles/cxxabi_objects.dir/cxa_default_handlers.cpp.obj and in src/cmakefiles/cxxabi_objects.dir/stdlib_exception.cpp.obj
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
[19/19] Linking CXX static library lib/libc++abi.a
ninja: build stopped: subcommand failed.
[1/2] Linking CXX shared library src/libc++abi.dll
FAILED: src/libc++abi.dll lib/libc++abi.dll.a
: && /Users/martell/llvm/usr/bin/x86_64-w64-mingw32-clang++  -Wa,-mbig-obj -Werror=date-time -std=gnu++11 -w --target=x86_64-w64-mingw32 -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -std=c++11 -fstrict-aliasing -fno-exceptions  --target=x86_64-w64-mingw32 -rtlib=compiler-rt -nodefaultlibs -shared -o src/libc++abi.dll -Wl,--out-implib,lib/libc++abi.dll.a -Wl,--major-image-version,1,--minor-image-version,0 src/CMake
Files/cxxabi_objects.dir/cxa_aux_runtime.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_default_handlers.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_demangle.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_exception_storage.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_guard.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_handlers.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_unexpected.cpp.obj src/CMakeFiles/
cxxabi_objects.dir/cxa_vector.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_virtual.cpp.obj src/CMakeFiles/cxxabi_objects.dir/stdlib_exception.cpp.obj src/CMakeFiles/cxxabi_objects.dir/stdlib_stdexcept.cpp.obj src/CMakeFiles/cxxabi_objects.dir/stdlib_typeinfo.cpp.obj src/CMakeFiles/cxxabi_objects.dir/abort_message.cpp.obj src/CMakeFiles/cxxabi_objects.dir/fallback_malloc.cpp.obj src/CMakeFiles/cxxabi_object
s.dir/private_typeinfo.cpp.obj src/CMakeFiles/cxxabi_objects.dir/stdlib_new_delete.cpp.obj src/CMakeFiles/cxxabi_objects.dir/cxa_noexception.cpp.obj  -lmingw32 /Users/martell/llvm/usr/lib/clang/5.0.0/lib/windows/libclang_rt.builtins-x86_64.a -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 /Users/martell/llvm/usr/lib/clang/5.0.0/lib/windows/libclang_rt.builtins-x86_64.a -lmol
dname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && :
/Users/martell/llvm/usr/bin/lld: error: duplicate symbol: _ZTISt9exception in src/cmakefiles/cxxabi_objects.dir/cxa_default_handlers.cpp.obj and in src/cmakefiles/cxxabi_objects.dir/stdlib_exception.cpp.obj
/Users/martell/llvm/usr/bin/lld: error: duplicate symbol: _ZTSSt9exception in src/cmakefiles/cxxabi_objects.dir/cxa_default_handlers.cpp.obj and in src/cmakefiles/cxxabi_objects.dir/stdlib_exception.cpp.obj
```

**Comment by martell** [comment] 2017-05-21 13:44
Just to follow up, if I build with `LIBCXXABI_SILENT_TERMINATE`

```
/Users/martell/llvm/usr/bin/lld: warning: src/cmakefiles/cxxabi_objects.dir/stdlib_stdexcept.cpp.obj: undefined symbol: __imp__ZTVSt11logic_error
/Users/martell/llvm/usr/bin/lld: warning: src/cmakefiles/cxxabi_objects.dir/stdlib_stdexcept.cpp.obj: undefined symbol: __imp__ZTVSt13runtime_error
/Users/martell/llvm/usr/bin/lld: warning: src/cmakefiles/cxxabi_objects.dir/stdlib_typeinfo.cpp.obj: undefined symbol: __imp__ZTVSt8bad_cast
/Users/martell/llvm/usr/bin/lld: warning: src/cmakefiles/cxxabi_objects.dir/stdlib_typeinfo.cpp.obj: undefined symbol: __imp__ZTVSt10bad_typeid
```

**Comment by mati865** [comment] 2017-05-21 17:37
@martell Similar errors: https://reviews.llvm.org/P7983$704
Errors explained: http://lists.llvm.org/pipermail/cfe-dev/2017-April/053530.html

**Comment by martell** [comment] 2017-05-21 18:19
Bit of an update.

hey @mati865,
For context I am not using gcc or libstdc++ or binutils at all.
This was all working for be before xmas. :/

It seems mostly related to a regression in lld regarding duplicate symbols.
I made a quick hack to implement /FORCE:MULTIPLE in lld
I have it all fixed and working again now.

I done some tests with atomics types and they seem to work well.

I then started playing around with the new win32 c++ threads support in llvm without pthread.
It has other issues though.
Most notably I need to implement exception handling in libunwind.

```
~/llvm/usr/bin/x86_64-w64-mingw32-clang++ thread.cpp
/Users/martell/llvm/usr/bin/lld: warning: libc++.a(system_error.cpp.obj): undefined symbol: _ZTISt13runtime_error
/Users/martell/llvm/usr/bin/lld: warning: libc++abi.a(private_typeinfo.cpp.obj): undefined symbol: __imp__ZNSt9type_infoD2Ev
/Users/martell/llvm/usr/bin/lld: warning: libc++abi.a(stdlib_stdexcept.cpp.obj): undefined symbol: __imp__ZTVSt13runtime_error
/Users/martell/llvm/usr/bin/lld: warning: libc++.a(locale_win32.cpp.obj): undefined symbol: _get_current_locale
/Users/martell/llvm/usr/bin/lld: warning: libc++.a(future.cpp.obj): undefined symbol: _ZTISt11logic_error
/Users/martell/llvm/usr/bin/lld: warning: libc++.a(stdexcept.cpp.obj): undefined symbol: _ZTVSt11logic_error
/Users/martell/llvm/usr/bin/lld: warning: libc++.a(stdexcept.cpp.obj): undefined symbol: _ZTVSt13runtime_error
/Users/martell/llvm/usr/bin/lld: warning: libc++abi.a(cxa_exception.cpp.obj): undefined symbol: _Unwind_RaiseException
/Users/martell/llvm/usr/bin/lld: warning: libc++abi.a(cxa_exception.cpp.obj): undefined symbol: _Unwind_DeleteException
```

**Closed** 2018-05-17 05:46 UTC
