### ISSUE TITLE
ssl module in Python is not available.

### ISSUE THREAD

**Issue by loganmc10** [Alexpux/MINGW-packages#4582] opened 2018-10-23 03:20 UTC
I installed pip via pacman then I try this:

```python3 -m pip install awscli```

This used to work, but now I get:

```pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.```

**Comment by lovetox** [comment] 2018-10-23 06:19
I experience this also, this was fixed #4470 but seems to be still or again broken

https://ci.appveyor.com/project/lovetox/gajim/builds/19701666/job/l8vnsgk08d0445kn

@lazka do you also experience this?

**Comment by lazka** [comment] 2018-10-23 08:32
@lovetox ah, right appveyor is broken atm, we'll have to wait for https://github.com/appveyor/ci/issues/2571

@loganmc10 does it fail locally for you or on appveyor?

**Comment by loganmc10** [comment] 2018-10-23 12:07
This is on appveyor

**Comment by loganmc10** [comment] 2018-10-23 14:39
Are you sure it is related to that issue? My builds were working up until 6 days ago, that issue was reported back in August.

**Comment by lazka** [comment] 2018-10-23 16:02
Not 100% sure, no. Our openssl was updated to the conflicting naming 3 weeks ago, so it should have started then. Maybe newer Python uses newer openssl APIs which only now lead to problems.

You can test by deleting "C:\Windows\System32\libssl*.dll" "C:\Windows\System32\libcrypto*.dll" on appveyor.

**Comment by lovetox** [comment] 2018-10-23 19:17
I had a build 3 days ago that used 

`mingw-w64-x86_64-python3-3.7.0-15-any.pkg.tar.xz`

now it uses

`mingw-w64-x86_64-python3-3.7.1-2-any.pkg.tar.xz`

**Comment by lovetox** [comment] 2018-10-23 20:48
The problem is solved for me with adding these 2 lines to the appveyor script

```
  - del C:\Windows\System32\libssl-*.dll C:\Windows\system32\libcrypto-*.dll
  - del C:\Windows\SysWOW64\libssl-*.dll C:\Windows\SysWOW64\libcrypto-*.dll
```

so indeed an appveyor problem

**Comment by lazka** [comment] 2018-10-24 07:00
Thanks for testing it!

**Comment by gbtami** [comment] 2018-11-06 20:34
@lovetox unfortunately adding those 2 lines doesn't worked for pychess on appveyor:
```
python3 --version
Python 3.7.1
pip3 install pexpect
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting pexpect
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pexpect/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pexpect/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pexpect/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pexpect/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pexpect/
  Could not find a version that satisfies the requirement pexpect (from versions: )
No matching distribution found for pexpect
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Command exited with code 1
```

**Comment by lovetox** [comment] 2018-11-06 21:48
Maybe you can share the appveyor link to your logs, one thing i found in your appveyor script is that you do a `pacman -Syu` but dont follow it up with a `pacman -Su` as recommended on msys2.org

maybe you can have a look at our build logs, and see if there is a difference that could matter
https://ci.appveyor.com/project/yann-l/gajim/builds/20098372/job/8tj89vdow5jbhm4r

**Comment by gbtami** [comment] 2018-11-06 22:42
`pacman -Su` did the trick. Thx a lot!

**Comment by lazka** [comment] 2018-11-30 20:49
I guess we can close this. If there is anything still not working please speak up :)

**Closed by lazka** 2018-11-30 20:49 UTC

**Comment by alejandrohd** [comment] 2019-02-16 06:44
This symptom ("ssl module in Python is not available") seems to be triggered by different possible causes. I spent 1 day struggling with it and found many suggestions that worked for some people but not for others, or me. What worked for me was to remove 2 spurious files as per issue https://github.com/appveyor/ci/issues/2571. Specifically, somehow 5 days ago these two files appeared in my C:/Windows/System32:  libcrypto-1_1-x64.dll and libssl-1_1-x64.dll (not sure what other software put them in there, but they sure broke things). I moved them to another folder not in the PATH, and now things work for my -Python finds SSL and Conda is now able to work e.g., create environments, and pip install now works instead of failing because of the SSL problem. Maybe this helps others.

**Comment by BishnoiAmit** [comment] 2019-02-22 03:14
Installation of OpenSSL from this link (https://slproweb.com/products/Win32OpenSSL.html) worked for me.

**Comment by kraken9x** [comment] 2019-03-11 20:20
Thank you @BishnoiAmit , I installed openssl from your link and it worked.

**Comment by StarWolf3000** [comment] 2019-03-12 07:33
This will obiously break other applications, that rely on OpenSSL in the Windows path and require another version.

**Comment by DTasev** [comment] 2019-03-22 09:52
@StarWolf3000 In that case OpenSSL gives you the option to install the libaries in `OpenSSL\bin`, and users can manually add that path to their PATH before running pip

**Comment by oducille** [comment] 2019-05-25 19:58
That does not work with python for me. It seems to be asking for a python module!

**Comment by jain6968** [comment] 2020-02-11 06:41
@BishnoiAmit this worked for me as well. thanks!

**Comment by sundaramseth** [comment] 2020-02-20 18:07
problem solved after download ---/https://slproweb.com/products/Win32OpenSSL.html

**Comment by sundaramseth** [comment] 2020-02-20 18:07
thanks buddy

**Comment by tatianapg** [comment] 2020-04-15 01:50
> 
> 
> This symptom ("ssl module in Python is not available") seems to be triggered by different possible causes. I spent 1 day struggling with it and found many suggestions that worked for some people but not for others, or me. What worked for me was to remove 2 spurious files as per issue [appveyor/ci#2571](https://github.com/appveyor/ci/issues/2571). Specifically, somehow 5 days ago these two files appeared in my C:/Windows/System32: libcrypto-1_1-x64.dll and libssl-1_1-x64.dll (not sure what other software put them in there, but they sure broke things). I moved them to another folder not in the PATH, and now things work for my -Python finds SSL and Conda is now able to work e.g., create environments, and pip install now works instead of failing because of the SSL problem. Maybe this helps others.

Hi Alejandohd, this worked for me(April 14, 2020).  I spent a day a hald trying to solve this problem.  I removed the files you mentioned from my windows directory, and then Anaconda Navigator worked.
Thanks a lot!
