### ISSUE TITLE
cmake cannot find python2

### ISSUE THREAD

**Issue by chaffra** [Alexpux/MINGW-packages#668] opened 2015-06-10 22:08 UTC
When running from mingw32_shell.bat with python2 installed cmake

find_package(PythonInterp 2) cannot find python in cmake. It returns 

Could NOT find PythonInterp: Found unsuitable version "1.4", but required is at least "2" (found E:/msys32/mingw32/bin/python2)

cmake breaks here 

execute_process(COMMAND "${PYTHON_EXECUTABLE}" -c
                            "import sys; sys.stdout.write(';'.join([str(x) for x in sys.version_info[:3]]))"
                    OUTPUT_VARIABLE _VERSION
                    RESULT_VARIABLE _PYTHON_VERSION_RESULT
                    ERROR_QUIET)

_PYTHON_VERSION_RESULT is set to "%1 is not a valid Win32 application"

why is python2 not a valid Win32 app?

**Comment by mingwandroid** [comment] 2015-06-10 22:31
I cannot reproduce this. My test was:

    $ echo "find_package(PythonInterp 2)" > CMakeLists.txt
    $ cmake -G'MSYS Makefiles'

The result was:

    -- Found PythonInterp: E:/msys64/mingw32/bin/python2.exe (found suitable version "2.7.10", minimum required is "2")

**Comment by mingwandroid** [comment] 2015-06-10 22:33
Please try my test with:

    cmake -G'MSYS Makefiles' --debug-output --trace

.. and paste your results here.

**Comment by chaffra** [comment] 2015-06-11 01:37
Thanks Ray,

the problem was that I had the PYTHON_EXECUTABLE variable set to python2 instead of python2.exe
python2 is a bash file and cannot be executed in cmd.exe

**Comment by mingwandroid** [comment] 2015-06-11 07:56
Ok, closing.

**Closed by mingwandroid** 2015-06-11 07:56 UTC
