### ISSUE TITLE
mingw-w64-glib2 doesn't install documentation

### ISSUE THREAD

**Issue by liberforce** [Alexpux/MINGW-packages#2355] opened 2017-03-30 13:41 UTC
It seems the gtk-doc documentation is not installed, which makes it not show in the devhelp help browser. It should either pass the --enable-gtk-doc argument to the configure script or have a specific package of pre-compiled docs.

**Comment by mati865** [comment] 2017-03-30 16:31
Duplicate of https://github.com/Alexpux/MINGW-packages/issues/2328

**Comment by lazka** [comment] 2018-01-24 18:50
mingw-w64-glib2 in the repo includes documentation now

**Closed by lazka** 2018-01-24 18:50 UTC
