### ISSUE TITLE
qt5 depends

### ISSUE THREAD

**Issue by ustsv** [Alexpux/MINGW-packages#3038] opened 2017-10-12 13:00 UTC
qt5 depends on pcre2 (not only pcre and/or?) 
Qt5Core.dll import libpcre2-16-0.dll

**Comment by mati865** [comment] 2017-10-12 13:07
duplicate of https://github.com/Alexpux/MINGW-packages/issues/3036

**Closed** 2018-10-02 05:42 UTC
