### ISSUE TITLE
python-h5py fails to build

### ISSUE THREAD

**Issue by fracting** [Alexpux/MINGW-packages#1083] opened 2016-02-21 22:48 UTC
[python-h5py.txt](https://github.com/Alexpux/MINGW-packages/files/139900/python-h5py.txt)

The package python-h5py fails to build in our Drone CI, I was not sure if it is a false positive introduced by Wine, I created 
https://bugs.wine-staging.com/show_bug.cgi?id=649 for record.

Later then I run the build on Windows, and it fails as well but in another way.

Attachment is the build log for me. Anyone could confirm if it works or doesn't work on Windows?

Thanks!

**Comment by elieux** [comment] 2016-02-22 07:56
I got one `Download error on https://pypi.python.org/simple/pkgconfig/: [Errno 10054] An existing connection was forcibly closed by the remote host -- Some packages may not be found!`.

On second try, I see `setuptools.sandbox.SandboxViolation: SandboxViolation: mkdir('c:/users/ether/appdata/local/temp/1/easy_install-dqspwk/pkgconfig-1.1.0/.eggs',) {}`.

After a little investigation in `lib/python2.7/site-packages/setuptools/sandbox.py`, it looks like the `self._prefix` is failing to match due to a wrong slash being appended.

```
print(repr(path))
print(repr(os.path.normcase(os.path.realpath(path))))
print(repr(self._exceptions))
print(repr(self._exception_patterns))
print(repr(self._sandbox))
print(repr(self._prefix))
```

```
'./.eggs'
'c:\\users\\ether\\appdata\\local\\temp\\1\\easy_install-n9g_wi\\pkgconfig-1.1.0\\.eggs'
['\\\\.\\nul']
['.*lib2to3.*\\.pickle$']
'c:\\users\\ether\\appdata\\local\\temp\\1\\easy_install-n9g_wi\\pkgconfig-1.1.0'
'c:\\users\\ether\\appdata\\local\\temp\\1\\easy_install-n9g_wi\\pkgconfig-1.1.0/'
```

Line 383: `self._prefix = os.path.join(self._sandbox,'')`

Happens only when `MSYSTEM=MINGW*`. Are we missing slash conversions in `os.path.realpath`, @mingwandroid?

**Comment by elieux** [comment] 2016-02-22 07:58
Correction, `realpath` return forward slashes as expected, it's `os.path.normcase` that converts them back to backslashes.

**Comment by mingwandroid** [comment] 2016-02-22 08:34
We've had a bug with this one for ages. I really hope this is it. I'll take a quick look later.

**Comment by elieux** [comment] 2016-02-22 12:06
I can confirm that the build works with v2.7.11-2 of mingw-w64-python2. (I had to run makepkg-mingw 12 times due to those pesky download errors though.)

Close or keep the issue until the package is uploaded?

**Comment by fracting** [comment] 2016-02-22 12:09
I suggest to keep it until new package is uploaded, I'll update our CI server and trigger a new CI build after that.

**Comment by fracting** [comment] 2016-02-25 21:27
I upgrade everything in Drone CI, but it still fails: http://wine-ci.org/fracting/MINGW-packages/37

Could you read the log and tell me if the python packages installed in CI is v2.7.11-2? Is it uploaded anyway? I'll have to check if it is a Wine bug if the python2 package is confirmed to be updated.

Thanks a lot!

**Comment by Alexpux** [comment] 2016-04-08 12:54
Building fine for me

**Closed by Alexpux** 2016-04-08 12:54 UTC
