### ISSUE TITLE
mingw-w64-i686-gdb crash on windows 7 64bit OS ( both gdb version 7.9 and 7.12 )

### ISSUE THREAD

**Issue by ninepillars** [Alexpux/MINGW-packages#2203] opened 2017-02-23 02:01 UTC
Either msys2-64bit or msys2-32bit has the same issue.

when I start gdb( mingw-w64-i686 version ), type gdb commands such as r( run ), l (list), then it crashes!
with this message:  "This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

the issue does **NOT** happend on mingw-w64-x86_64-gdb package and msys2/gdb ( both 32bit and 64bit ) packages, **ONLY** mingw-w64-i686-gdb has this problem.

**Comment by mati865** [comment] 2017-02-23 10:53
Duplicate of https://github.com/Alexpux/MINGW-packages/issues/1862

**Comment by Alexpux** [comment] 2017-03-22 10:33
Seems fixed now.

**Closed by Alexpux** 2017-03-22 10:33 UTC
